"""baseline schema: sources, documents, chunks, embeddings, tags, conversations,
messages, retrievals, feedback, audit_log, jobs + pgvector/full-text indexes

Hand-written (not autogenerated) so we control the pgvector extension, the GENERATED
tsvector column, and the HNSW/GIN index DDL. This file is the source of truth for the
Phase 0 schema; ORM models mirror it. See docs/data-model/er-diagram.md and ADRs 0002–0004.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-01
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBED_DIM = 384  # all-MiniLM-L6-v2 — ADR-0002


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Generic updated_at trigger (Postgres-depth signal; keeps app code from forgetting it).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )

    op.execute(
        """
        CREATE TABLE sources (
            id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            type        text NOT NULL CHECK (type IN
                        ('notes_folder','github','rss','pdf_upload','bookmark','research_note','manual')),
            name        text NOT NULL,
            uri         text,
            config      jsonb NOT NULL DEFAULT '{}'::jsonb,
            created_at  timestamptz NOT NULL DEFAULT now(),
            updated_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE TRIGGER trg_sources_updated_at BEFORE UPDATE ON sources "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )

    op.execute(
        """
        CREATE TABLE documents (
            id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            source_id    bigint NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
            title        text NOT NULL,
            external_id  text,
            content_type text,
            content_hash char(64) NOT NULL,
            raw_text     text,
            metadata     jsonb NOT NULL DEFAULT '{}'::jsonb,
            status       text NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending','chunked','embedded','failed')),
            ingested_at  timestamptz,
            created_at   timestamptz NOT NULL DEFAULT now(),
            updated_at   timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_documents_source_hash UNIQUE (source_id, content_hash)
        )
        """
    )
    op.execute("CREATE INDEX ix_documents_source_id ON documents (source_id)")
    op.execute("CREATE INDEX ix_documents_status ON documents (status)")
    op.execute("CREATE INDEX ix_documents_metadata ON documents USING gin (metadata jsonb_path_ops)")
    op.execute(
        "CREATE TRIGGER trg_documents_updated_at BEFORE UPDATE ON documents "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )

    op.execute(
        """
        CREATE TABLE chunks (
            id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            document_id bigint NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            chunk_index int NOT NULL,
            content     text NOT NULL,
            token_count int,
            char_start  int,
            char_end    int,
            tsv         tsvector GENERATED ALWAYS AS (to_tsvector('english', content)) STORED,
            metadata    jsonb NOT NULL DEFAULT '{}'::jsonb,
            created_at  timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_chunks_doc_index UNIQUE (document_id, chunk_index)
        )
        """
    )
    op.execute("CREATE INDEX ix_chunks_document_id ON chunks (document_id)")
    op.execute("CREATE INDEX ix_chunks_tsv ON chunks USING gin (tsv)")

    op.execute(
        f"""
        CREATE TABLE embeddings (
            id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            chunk_id   bigint NOT NULL REFERENCES chunks(id) ON DELETE CASCADE,
            model      text NOT NULL,
            dim        smallint NOT NULL,
            embedding  vector({EMBED_DIM}) NOT NULL,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_embeddings_chunk_model UNIQUE (chunk_id, model)
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_embeddings_hnsw ON embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    op.execute(
        """
        CREATE TABLE tags (
            id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name       text NOT NULL UNIQUE,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE document_tags (
            document_id bigint NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            tag_id      bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
            PRIMARY KEY (document_id, tag_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_document_tags_tag_id ON document_tags (tag_id)")

    op.execute(
        """
        CREATE TABLE conversations (
            id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            title      text,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON conversations "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )

    op.execute(
        """
        CREATE TABLE messages (
            id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
            role            text NOT NULL CHECK (role IN ('user','assistant','system')),
            content         text NOT NULL,
            model           text,
            token_usage     jsonb,
            latency_ms      int,
            created_at      timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_messages_conversation ON messages (conversation_id, created_at)")

    op.execute(
        """
        CREATE TABLE retrievals (
            id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            message_id     bigint NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            chunk_id       bigint NOT NULL REFERENCES chunks(id) ON DELETE CASCADE,
            rank           int NOT NULL,
            score          double precision,
            vector_score   double precision,
            fulltext_score double precision,
            method         text NOT NULL CHECK (method IN ('vector','fulltext','hybrid')),
            created_at     timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_retrievals_message ON retrievals (message_id)")
    op.execute("CREATE INDEX ix_retrievals_chunk ON retrievals (chunk_id)")

    op.execute(
        """
        CREATE TABLE feedback (
            id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            message_id bigint NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            rating     smallint NOT NULL CHECK (rating IN (-1, 1)),
            comment    text,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_feedback_message ON feedback (message_id)")

    op.execute(
        """
        CREATE TABLE audit_log (
            id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            actor       text NOT NULL,
            action      text NOT NULL CHECK (action IN ('read','create','update','delete','export')),
            entity_type text NOT NULL,
            entity_id   bigint,
            detail      jsonb NOT NULL DEFAULT '{}'::jsonb,
            created_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_audit_log_entity ON audit_log (entity_type, entity_id)")

    op.execute(
        """
        CREATE TABLE jobs (
            id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            type         text NOT NULL CHECK (type IN ('ingest','embed','briefing','research')),
            payload      jsonb NOT NULL DEFAULT '{}'::jsonb,
            status       text NOT NULL DEFAULT 'queued'
                         CHECK (status IN ('queued','running','done','failed')),
            attempts     int NOT NULL DEFAULT 0,
            last_error   text,
            scheduled_at timestamptz NOT NULL DEFAULT now(),
            started_at   timestamptz,
            finished_at  timestamptz,
            created_at   timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_jobs_status_scheduled ON jobs (status, scheduled_at)")


def downgrade() -> None:
    for table in (
        "jobs",
        "audit_log",
        "feedback",
        "retrievals",
        "messages",
        "conversations",
        "document_tags",
        "tags",
        "embeddings",
        "chunks",
        "documents",
        "sources",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    # Extension left in place intentionally — other schemas may rely on it.
